destination_server: "download.goffinet.org"

vm:
  cpu: "2"
  disk_size: "40000"
  ram: "2048"

boot_command: >-
  {%- if type == 'redhat' -%}
    {%- if flavor == 'fedora' or label == 'centos10' -%}
  ["<up>e", "<down><down><end>",
  " inst.ks=http://{% raw %}{{ .HTTPIP }}:{{ .HTTPPort }}{% endraw %}/http/${var.config_file}",
  "<leftCtrlOn>x<leftCtrlOff>"]
    {%- elif label == 'almalinux10' or label == 'rocky10' -%}
  ["e","<down><down>","<leftCtrlOn>e<leftCtrlOff>","<spacebar>","biosdevname=0","<spacebar>","net.ifnames=0","<spacebar>","inst.text","<spacebar>","inst.ks=http://{% raw %}{{ .HTTPIP }}:{{ .HTTPPort }}{% endraw %}/http/${var.config_file}","<leftCtrlOn>x<leftCtrlOff>"]
    {%- else -%}
  ["<tab><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs><bs> inst.text inst.ks=http://{% raw %}{{ .HTTPIP }}:{{ .HTTPPort }}{% endraw %}/http/${var.config_file}<enter><wait>"]
    {%- endif -%}
  {%- elif type == 'debian' -%}
    {%- if flavor == 'ubuntu' and version == '2004' -%}
  ["<enter><enter><f6><esc><wait>",
  "<bs><bs><bs><bs>",
  "autoinstall net.ifnames=0 biosdevname=0 ip=dhcp ipv6.disable=1 ds=nocloud-net;s=http://{% raw %}{{ .HTTPIP }}:{{ .HTTPPort }}/http/${var.name}${var.version}/{% endraw %} ",
  "--- <enter>"]
    {%- elif flavor == 'ubuntu' and (version == '2204' or version == '2404') -%}
  ["c<wait>linux /casper/vmlinuz --- autoinstall ds={% raw %}"nocloud;s=http://{{ .HTTPIP }}:{{ .HTTPPort }}/http/${var.name}${var.version}/\"{% endraw %}<enter><wait>",
  "initrd /casper/initrd<enter><wait>",
  "boot<enter><wait>"]
    {%- elif flavor == 'debian' -%}
  ["<esc><wait>", "auto <wait>",
  "console-keymaps-at/keymap=us <wait>",
  "console-setup/ask_detect=false <wait>",
  "debconf/frontend=noninteractive <wait>",
  "debian-installer=en_US <wait>",
  "fb=false <wait>",
  "install <wait>",
  "kbd-chooser/method=us <wait>",
  "keyboard-configuration/xkb-keymap=us <wait>",
  "locale=en_US <wait>",
  "netcfg/get_hostname=${var.name}${var.version} <wait>",
  "preseed/url=http://{% raw %}{{ .HTTPIP }}:{{ .HTTPPort }}{% endraw %}/http/${var.config_file} <wait>", 
  "<enter><wait>"]
    {%- endif -%}
  {%- endif -%}

ssh_password_salt: >-
  mB3ZauOM8/HIycgS

ssh_password: >-
  {%- if type == 'redhat' or flavor == 'debian' -%}
  testtest
  {%- elif flavor == 'ubuntu' -%}
  ubuntu
  {%- endif -%}

ssh_username: >-
  {%- if type == 'redhat' or flavor == 'debian' -%}
  root
  {%- elif flavor == 'ubuntu' -%}
  ubuntu
  {%- endif -%}

additional_parameters: |
  {%- if type == 'redhat' -%}
  ssh_wait_timeout = "30m"
  boot_wait        = "10s"
  {%- elif type == 'debian' -%}
  boot_wait              = "10s"
  ssh_handshake_attempts = 500
  ssh_timeout            = "45m"
  ssh_wait_timeout       = "45m"
  host_port_max          = 2229
  host_port_min          = 2222
  http_port_max          = 10089
  http_port_min          = 10082
  {%- endif -%}

shell_provisioner: >-
  {%- if type == 'redhat' -%}
  ["dnf -y install python3 python3-pip",
  "pip3 install ansible"]
  {%- elif flavor == 'ubuntu' -%}
  ["sudo apt-get update",
  "sudo apt-get -y install software-properties-common",
  "sudo apt-add-repository --yes --update ppa:ansible/ansible",
  "sudo apt update",
  "sudo apt -y install ansible"]
  {% elif flavor == 'debian' %}
  ["apt-get update",
  "apt -y install ansible"]
  {%- endif -%}

packer_j2: "linux.pkr.hcl.j2"

response_j2: >-
  {%- if type == 'redhat' -%}
  kickstart.cfg.j2
  {%- elif flavor == 'ubuntu' -%}
  user-data.j2
  {%- elif flavor == 'debian' -%}
  preseed.cfg.j2
  {%- endif -%}
