- name: Set Ubuntu computed variables
  set_fact:
    label: "{{ item.flavor }}{{ item.version.split('.')[0] }}{{ item.version.split('.')[1] }}"
    version: "{{ item.version.split('.')[0] }}{{ item.version.split('.')[1] }}"
  when: item.flavor == "ubuntu"

- name: Set config_file
  set_fact:
    config_file: "user-data"

- name: Create image.pkr.hcl
  template:
    src: "linux.pkr.hcl.j2"
    dest: "{{ packer_templates_dir }}/{{ label }}.pkr.hcl"

- name: Create packer-templates directory
  file:
    dest: "{{ packer_templates_dir }}/http/{{ label }}"
    state: directory

- name: Create cloud-init file
  template:
    src: "user-data.j2"
    dest: "{{ packer_templates_dir }}/http/{{ label }}/{{ config_file }}"