- name: Set computed variables
  set_fact:
    label: "{{ item.flavor }}{{ item.version.split('.')[0] }}"
    version: "{{ item.version.split('.')[0] }}"

- name: Set config_file variable
  set_fact:
    config_file: "{{ label }}-kickstart.cfg"

- name: Create image.pkr.hcl
  template:
    src: "linux.pkr.hcl.j2"
    dest: "{{ packer_templates_dir }}/{{ label }}.pkr.hcl"

- name: Create packer-templates directory
  file:
    dest: "{{ packer_templates_dir }}/http"
    state: directory

- name: Create kickstart file
  template:
    src: "kickstart.cfg.j2"
    dest: "{{ packer_templates_dir }}/http/{{ config_file }}"