- name: set computed variables
  set_fact:
    label: "{{ item.flavor }}{{ item.version.split('.')[0] }}"
    version: "{{ item.version.split('.')[0] }}"

- name: set config_file
  set_fact:
    config_file: "{{ label }}-kickstart.cfg"

- name: Get checksum file
  vars:
    checksum_url: "{{ item.iso_url }}/{{ item.checksum_filename }}"
    iso_name: "{{ item.iso_name | regex_replace('\\.','\\\\.') }}"
  shell: curl -k -L -s {{ checksum_url }} | awk '/SHA256 \({{ iso_name }}\)/ {print $NF}'
  register: checksum_file

- debug:
    var: checksum_file
  tags: never

- set_fact:
    checksum: "{{ checksum_file.stdout }}"

- name: Create image.pkr.hcl
  template:
    src: "linux.pkr.hcl.j2"
    dest: "{{ packer_templates_dir }}/{{ label }}.pkr.hcl"

- name: Create packer-templates directory
  file:
    dest: "{{ packer_templates_dir }}/http"
    state: directory

- name: Create kickstart file
  template:
    src: "kickstart.cfg.j2"
    dest: "{{ packer_templates_dir }}/http/{{ config_file }}"