- name: Set debian type computed variables
  ansible.legacy.set_fact:
    type: "{{ item.type }}"
    flavor: "{{ item.flavor }}"

- block:
  - name: Set debian flavor computed variables
    ansible.legacy.set_fact:
      label: "{{ item.flavor }}{{ item.version.split('.')[0] }}"
      version: "{{ item.version.split('.')[0] }}"
  - name: Set debian flavor config_file
    ansible.legacy.set_fact:
      config_file: "{{ label }}-preseed.cfg"
  - name: Create debian flavor http directory
    ansible.legacy.file:
      dest: "{{ playbook_dir }}/http"
      state: directory
  - name: Create debian flavor preseed file
    ansible.legacy.template:
      src: "{{ item.response_j2 | default(response_j2) }}"
      dest: "{{ playbook_dir }}/http/{{ config_file }}"
  when: item.flavor == "debian"

- block:
  - name: Set ubuntu computed variables
    ansible.legacy.set_fact:
      label: "{{ item.flavor }}{{ item.version.split('.')[0] }}{{ item.version.split('.')[1] }}"
      version: "{{ item.version.split('.')[0] }}{{ item.version.split('.')[1] }}"
  - name: Create ubuntu cloud-init directory
    ansible.legacy.file:
      dest: "{{ playbook_dir }}/http/{{ label }}"
      state: directory
  - name: Create ubuntu user-data file
    ansible.legacy.template:
      src: "{{ item.response_j2 | default(response_j2) }}"
      dest: "{{ playbook_dir }}/http/{{ label }}/user-data"
  - name: Create ubuntu meta-data file
    ansible.legacy.template:
      src: "meta-data.j2"
      dest: "{{ playbook_dir }}/http/{{ label }}/meta-data"
  when: item.flavor == "ubuntu"

- name: Create pkr.hcl template
  ansible.legacy.template:
    src: "linux.pkr.hcl.j2"
    dest: "{{ label }}.pkr.hcl"
