- name: Set redhat computed variables
  ansible.legacy.set_fact:
    build_packer_templates_label: "{{ item.flavor }}{{ item.version.split('.')[0] }}"
    build_packer_templates_version: "{{ item.version.split('.')[0] }}"
    build_packer_templates_ks_suffix: "-kickstart.cfg"
    build_packer_templates_type: "{{ item.type }}"
    build_packer_templates_flavor: "{{ item.flavor }}"

- name: Set redhat config_file variable
  ansible.legacy.set_fact:
    build_packer_templates_config_file: "{{ build_packer_templates_label }}{{ build_packer_templates_ks_suffix }}"

- name: Create image.pkr.hcl
  ansible.legacy.template:
    src: "linux.pkr.hcl.j2"
    dest: "{{ playbook_dir }}/{{ label }}.pkr.hcl"

- name: Create redhat http directory
  ansible.legacy.file:
    dest: "{{ playbook_dir }}/http"
    state: directory

- name: Create redhat kickstart file
  ansible.legacy.template:
    src: "kickstart.cfg.j2"
    dest: "{{ playbook_dir }}/http/{{ config_file }}"
